Section "InputClass"
       Identifier "devname"
       Driver "libinput"
       MatchIsTouchpad "on"
       Option "Tapping" "on"
       Option "TappingDrag" "on"
       Option "TappingDragLock" "true"
       Option "NaturalScrolling" "true"
EndSection
